-- =============================================
-- Expense Tracker 2.0 - Supabase Schema
-- Run this in the Supabase SQL Editor
-- =============================================

-- ── Profiles (extends Supabase auth.users) ──
CREATE TABLE IF NOT EXISTS public.profiles (
  id         UUID        PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
  username   TEXT        UNIQUE NOT NULL,
  currency   TEXT        NOT NULL DEFAULT 'PHP',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own profile"
  ON public.profiles FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Users can update own profile"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile"
  ON public.profiles FOR INSERT
  WITH CHECK (auth.uid() = id);

-- ── Expenses ──
CREATE TABLE IF NOT EXISTS public.expenses (
  id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title        TEXT        NOT NULL,
  amount       DECIMAL(15,2) NOT NULL CHECK (amount > 0),
  expense_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  category     TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ
);

ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage own expenses"
  ON public.expenses FOR ALL
  USING (auth.uid() = user_id);

-- Optimised indexes
CREATE INDEX IF NOT EXISTS idx_expenses_user_id      ON public.expenses (user_id);
CREATE INDEX IF NOT EXISTS idx_expenses_date         ON public.expenses (expense_date);
CREATE INDEX IF NOT EXISTS idx_expenses_user_date    ON public.expenses (user_id, expense_date);

-- ── Auto-create profile on sign-up ──
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'username', split_part(NEW.email, '@', 1))
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ── Sample data (optional – run manually after signing up) ──
-- Replace '00000000-0000-0000-0000-000000000000' with your real user UUID
/*
INSERT INTO public.expenses (user_id, title, amount, expense_date, category) VALUES
('YOUR_USER_UUID', 'Morning Coffee',      4.50,  NOW(),                               'Food & Drinks'),
('YOUR_USER_UUID', 'Lunch at Restaurant', 18.75, NOW(),                               'Food & Drinks'),
('YOUR_USER_UUID', 'Gas Station',         45.00, NOW() - INTERVAL '1 day',            'Transportation'),
('YOUR_USER_UUID', 'Grocery Shopping',    85.20, NOW() - INTERVAL '2 days',           'Food & Drinks'),
('YOUR_USER_UUID', 'Netflix Subscription',15.99, NOW() - INTERVAL '5 days',           'Entertainment'),
('YOUR_USER_UUID', 'Gym Membership',      49.99, NOW() - INTERVAL '7 days',           'Health'),
('YOUR_USER_UUID', 'Book Purchase',       24.99, NOW() - INTERVAL '10 days',          'Education'),
('YOUR_USER_UUID', 'Movie Tickets',       28.00, NOW() - INTERVAL '15 days',          'Entertainment'),
('YOUR_USER_UUID', 'Restaurant Dinner',   65.50, NOW() - INTERVAL '20 days',          'Food & Drinks'),
('YOUR_USER_UUID', 'Uber Ride',           12.30, NOW() - INTERVAL '25 days',          'Transportation');
*/

-- ══════════════════════════════════════════
-- ADD THIS BLOCK for Salary Tracking feature
-- ══════════════════════════════════════════

-- ── Monthly Salaries ──
CREATE TABLE IF NOT EXISTS public.salaries (
  id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  month      VARCHAR(7)  NOT NULL,  -- format: 'YYYY-MM'  e.g. '2026-03'
  amount     DECIMAL(15,2) NOT NULL CHECK (amount >= 0),
  note       TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  UNIQUE (user_id, month)           -- one salary record per user per month
);

ALTER TABLE public.salaries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage own salaries"
  ON public.salaries FOR ALL
  USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_salaries_user_id ON public.salaries (user_id);
CREATE INDEX IF NOT EXISTS idx_salaries_month   ON public.salaries (user_id, month);
